import type { Locale } from './types';

export const copy: Record<Locale, Record<string, string>> = {
  en: {
    language: 'Bahasa Melayu',
    flightTheme: 'A cloud-bound celebration',
    checkIn: 'Invitation check-in',
    gateBody: 'This invitation is for invited guests. Enter the passcode shared with you to continue.',
    passcode: 'Passcode',
    passcodePlaceholder: 'Enter passcode',
    viewInvitation: 'View invitation',
    checking: 'Checking invitation...',
    invalidInvitation: 'We could not verify this invitation link or passcode. Check the details shared with you and try again.',
    connectionError: 'We could not reach invitation check-in. Check your connection and try again.',
    configurationError: 'Invitation check-in is not configured yet. Please contact Aleem or Nurulain for the complete link.',
    emptyPasscode: 'Enter your passcode to continue.',
    gateDate: 'August 2027 \u00b7 Singapore',
    missingTitle: 'Invitation link required',
    missingBody: 'Please use the complete private invitation link shared with you.',
    ticketReady: 'Your boarding pass is ready.',
    passenger: 'Passenger',
    hotel: 'Hotel',
    ballroom: 'Ballroom',
    terminal: 'Terminal',
    gate: 'Gate',
    flight: 'Flight',
    eventTime: 'Event time',
    event: 'Celebration',
    destination: 'Destination',
    departure: 'From',
    destinationName: 'CROWNE PLAZA',
    destinationAirport: 'Changi Airport',
    keepsake: 'Wedding keepsake \u00b7 Not valid for travel',
    board: 'Board Flight',
    skip: 'Skip journey',
    back: 'Back to boarding pass',
    controls: 'Invitation controls',
    reduceMotion: 'Reduce motion',
    reducedMotionOn: 'Reduced motion on',
    fullMotionOn: 'Travel motion on',
    welcome: 'Welcome aboard',
    welcomeBody: 'Please make yourself comfortable as we begin our journey above the clouds.',
    throughWindow: 'A new journey takes flight.',
    cabinAlt: 'A bright, quiet aircraft cabin leading towards the window',
    cloudsAlt: 'Soft sunlit clouds seen from an aircraft window',
    bismillah: 'Bismillahirrahmanirrahim',
    salam: "Assalamu'alaikum Warahmatullahi Wabarakatuh",
    formalInvite: 'With gratitude to Allah SWT, together with our families, we warmly invite you to celebrate the marriage of',
    blessing: 'Your presence and prayers will bring joy to our celebration. May Allah SWT bless this union with love, mercy and lasting happiness.',
    itinerary: 'Your itinerary',
    singaporeTime: 'All times are Singapore Time (SGT).',
    calendar: 'Add to calendar',
    calendarBusy: 'Preparing calendar...',
    calendarFailed: 'We could not prepare the calendar file. Please try again.',
    directions: 'Get directions',
    newTab: 'opens in a new tab',
    venue: 'Your destination',
    address: '75 Airport Boulevard, Singapore 819664',
    gettingHere: 'Getting here',
    travelMrt: 'MRT: Alight at Changi Airport station and follow signs to Terminal 3 and Crowne Plaza.',
    travelJewel: 'From Terminal 3 or Jewel: Follow the covered walkways and hotel signs to Crowne Plaza.',
    travelCar: 'By car, taxi or private hire: Use Crowne Plaza Changi Airport, 75 Airport Boulevard, as your destination and alight at the hotel entrance.',
    travelParking: 'Parking: Follow signs to the hotel or Terminal 3 car parks. Availability and prevailing charges apply.',
    travelTime: 'Please allow extra time during busy airport periods.',
    rsvpTitle: 'Confirm your attendance',
    respondBy: 'Response deadline',
    previewTitle: 'RSVP preview',
    previewBody: 'The invitation journey is ready, but RSVP is not open yet while response storage is being connected.',
    closedTitle: 'RSVP has closed',
    closedBody: 'Online responses are no longer being accepted.',
    name: 'Your name',
    attendancePrefix: 'Will you attend',
    oneAnswer: 'One response covers all celebrations listed for this day.',
    attending: 'Yes, I/we will attend',
    declining: 'No, I/we cannot attend',
    partySize: 'Number attending, including you',
    message: 'Message for Aleem & Nurulain (optional)',
    characters: 'Up to 500 characters',
    send: 'Send RSVP',
    sending: 'Sending...',
    clear: 'Clear saved response',
    saved: 'Your unfinished response is saved on this device so you can return later.',
    privacy: 'We collect only your name, attendance, party size and optional message for this wedding RSVP.',
    review: 'Please review the highlighted fields.',
    nameError: 'Enter your name.',
    attendanceError: 'Select an attendance response.',
    partyError: 'Enter a whole number of 1 or more.',
    messageError: 'Your message must be 500 characters or fewer.',
    success: 'Your RSVP has been received. Thank you for responding.',
    duplicate: 'This RSVP was already received. No duplicate response was created.',
    failed: 'We could not send your RSVP. Your answers are still saved on this device. Check your connection and try again.',
    unconfirmed: 'We could not confirm whether your RSVP reached us. Your answers and response ID are still saved; it is safe to try again.',
    conflict: 'This saved response ID was already used for different answers. Please clear the saved response and submit again.',
    expired: 'Your invitation session has expired. Enter the passcode again; your saved response will remain on this device.',
    retrySession: 'Check in again',
    journeyLabel: 'Your journey to our celebration',
    footer: 'Aleem & Nurulain \u00b7 Our Flight',
  },
  ms: {
    language: 'English',
    flightTheme: 'Sebuah perayaan di awan',
    checkIn: 'Daftar Masuk Jemputan',
    gateBody: 'Jemputan ini adalah untuk tetamu yang diundang. Masukkan kod laluan yang dikongsikan dengan anda untuk meneruskan.',
    passcode: 'Kod laluan',
    passcodePlaceholder: 'Masukkan kod laluan',
    viewInvitation: 'Lihat jemputan',
    checking: 'Sedang menyemak jemputan...',
    invalidInvitation: 'Kami tidak dapat mengesahkan pautan jemputan atau kod laluan ini. Semak maklumat yang dikongsikan dengan anda dan cuba lagi.',
    connectionError: 'Kami tidak dapat menghubungi daftar masuk jemputan. Semak sambungan internet dan cuba lagi.',
    configurationError: 'Daftar masuk jemputan belum dikonfigurasikan. Sila hubungi Aleem atau Nurulain untuk pautan lengkap.',
    emptyPasscode: 'Masukkan kod laluan untuk meneruskan.',
    gateDate: 'Ogos 2027 \u00b7 Singapura',
    missingTitle: 'Pautan jemputan diperlukan',
    missingBody: 'Sila gunakan pautan jemputan peribadi lengkap yang dikongsikan dengan anda.',
    ticketReady: 'Pas masuk anda sudah tersedia.',
    passenger: 'Penumpang',
    hotel: 'Hotel',
    ballroom: 'Dewan',
    terminal: 'Terminal',
    gate: 'Pintu',
    flight: 'Penerbangan',
    eventTime: 'Waktu majlis',
    event: 'Majlis',
    destination: 'Destinasi',
    departure: 'Dari',
    destinationName: 'CROWNE PLAZA',
    destinationAirport: 'Changi Airport',
    keepsake: 'Kenang-kenangan perkahwinan \u00b7 Tidak sah untuk perjalanan',
    board: 'Naik Pesawat',
    skip: 'Langkau perjalanan',
    back: 'Kembali ke pas masuk',
    controls: 'Kawalan jemputan',
    reduceMotion: 'Kurangkan animasi',
    reducedMotionOn: 'Animasi dikurangkan',
    fullMotionOn: 'Animasi perjalanan diaktifkan',
    welcome: 'Selamat datang',
    welcomeBody: 'Sila duduk dengan selesa sementara kita memulakan perjalanan di atas awan.',
    throughWindow: 'Sebuah perjalanan baharu bermula.',
    cabinAlt: 'Kabin pesawat yang terang dan tenang menuju ke tingkap',
    cloudsAlt: 'Awan lembut disinari matahari dilihat dari tingkap pesawat',
    bismillah: 'Bismillahirrahmanirrahim',
    salam: "Assalamu'alaikum Warahmatullahi Wabarakatuh",
    formalInvite: 'Dengan penuh kesyukuran ke hadrat Allah SWT, kami bersama keluarga dengan sukacitanya menjemput Tuan/Puan untuk meraikan majlis perkahwinan kami',
    blessing: 'Kehadiran serta doa restu Tuan/Puan akan menyerikan majlis kami. Semoga Allah SWT memberkati ikatan ini dengan kasih sayang, rahmat dan kebahagiaan yang berkekalan.',
    itinerary: 'Itinerari anda',
    singaporeTime: 'Semua waktu mengikut Waktu Singapura (SGT).',
    calendar: 'Tambah ke kalendar',
    calendarBusy: 'Sedang menyediakan kalendar...',
    calendarFailed: 'Kami tidak dapat menyediakan fail kalendar. Sila cuba lagi.',
    directions: 'Dapatkan arah',
    newTab: 'dibuka dalam tab baharu',
    venue: 'Destinasi anda',
    address: '75 Airport Boulevard, Singapore 819664',
    gettingHere: 'Cara ke sini',
    travelMrt: 'MRT: Turun di Stesen MRT Changi Airport, kemudian ikut papan tanda ke Terminal 3 dan Crowne Plaza.',
    travelJewel: 'Dari Terminal 3 atau Jewel: Ikuti laluan berbumbung serta papan tanda hotel ke Crowne Plaza.',
    travelCar: 'Kereta, teksi atau khidmat sewa persendirian: Tetapkan Crowne Plaza Changi Airport, 75 Airport Boulevard, sebagai destinasi dan turun di pintu masuk hotel.',
    travelParking: 'Tempat letak kereta: Ikut papan tanda ke tempat letak kereta hotel atau Terminal 3. Tertakluk pada ketersediaan dan kadar semasa.',
    travelTime: 'Sila luangkan masa tambahan ketika lapangan terbang sibuk.',
    rsvpTitle: 'Sila Sahkan Kehadiran',
    respondBy: 'Tarikh akhir jawapan',
    previewTitle: 'Pratonton RSVP',
    previewBody: 'Perjalanan jemputan sudah tersedia, tetapi RSVP belum dibuka sementara penyimpanan jawapan sedang disambungkan.',
    closedTitle: 'RSVP telah ditutup',
    closedBody: 'Jawapan dalam talian tidak lagi diterima.',
    name: 'Nama anda',
    attendancePrefix: 'Adakah anda akan menghadiri',
    oneAnswer: 'Satu jawapan merangkumi semua majlis yang disenaraikan untuk hari ini.',
    attending: 'Ya, saya/kami akan hadir',
    declining: 'Tidak, saya/kami tidak dapat hadir',
    partySize: 'Bilangan yang hadir, termasuk anda',
    message: 'Ucapan untuk Aleem & Nurulain (pilihan)',
    characters: 'Sehingga 500 aksara',
    send: 'Hantar RSVP',
    sending: 'Sedang menghantar...',
    clear: 'Padam jawapan tersimpan',
    saved: 'Jawapan yang belum dihantar disimpan pada peranti ini supaya anda boleh menyambung kemudian.',
    privacy: 'Kami hanya mengumpul nama, kehadiran, bilangan tetamu dan ucapan pilihan untuk RSVP perkahwinan ini.',
    review: 'Sila semak ruangan yang ditandakan.',
    nameError: 'Masukkan nama anda.',
    attendanceError: 'Pilih jawapan kehadiran.',
    partyError: 'Masukkan nombor bulat 1 atau lebih.',
    messageError: 'Ucapan anda mestilah 500 aksara atau kurang.',
    success: 'RSVP anda telah diterima. Terima kasih atas maklum balas anda.',
    duplicate: 'RSVP ini telah diterima sebelum ini. Tiada jawapan pendua direkodkan.',
    failed: 'Kami tidak dapat menghantar RSVP anda. Jawapan anda masih tersimpan pada peranti ini. Semak sambungan internet dan cuba lagi.',
    unconfirmed: 'Kami tidak dapat mengesahkan sama ada RSVP anda telah diterima. Jawapan dan ID respons masih disimpan; anda boleh mencuba lagi dengan selamat.',
    conflict: 'ID respons tersimpan ini telah digunakan untuk jawapan yang berbeza. Padam jawapan tersimpan dan hantar sekali lagi.',
    expired: 'Sesi jemputan anda telah tamat. Masukkan semula kod laluan; jawapan tersimpan akan kekal pada peranti ini.',
    retrySession: 'Daftar masuk semula',
    journeyLabel: 'Perjalanan anda ke majlis kami',
    footer: 'Aleem & Nurulain \u00b7 Our Flight',
  },
};
